services:
  scraper:
    restart: unless-stopped
    build:
      context: ./scraper/
      dockerfile: Dockerfile
    container_name: NavarchScraper
    volumes:
      - ./data:/usr/src/scraper/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    tty: true
    stdin_open: true
    cpus: "2"
    mem_limit: 400m

  server:
    restart: unless-stopped
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: NavarchServer
    networks:
      - proxy
    ports:
      - "3000:3000"
    mem_limit: 400m
    cpus: "1"
    volumes:
      - ./data:/data:ro
      #environment:
      #DB: "/data"

networks:
  proxy:
    external: true
