[package]
name = "Navarch"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11"
futures = "0.3"
indicatif = "0.17.8"
reqwest = { version = "0.12", features = ["cookies"] }
tokio = { version = "1.0", features = ["full"] }
sqlite = "0.36.1"
serde_json = "1.0"
html5ever = "0.29.0"
